Feat: Storybook Color Tokens and Webpack Build
credinvest/cred-ui pull request #13
Opened 2023-07-27 19:45 UTC by usmaniqbal998

### Things done in this PR

- Storybook upgraded to latest and shifted to vite based builds
- Module bundling moved from rollup to webpack because rollup was not generating css files
- Base color tokens added
- Semantic color tokens added

![Screenshot 2023-07-27 at 9 42 40 PM](https://github.com/credinvest/cred-ui/assets/26964912/fd29f89c-8358-402d-9a94-05f8a8bf3756)

2023-07-27 20:14 UTC, eraymeric requested changes

2023-07-27 20:14 UTC, eraymeric commented on src/index.ts
is this intentional change? Are we still able to use previous components when we remove exporting?

2023-07-27 20:14 UTC, eraymeric commented on src/components/index.ts
same question with src/index.ts

2023-07-27 20:25 UTC, usmaniqbal998 commented on src/index.ts
Oh sorry i forgot to update this . Let me update

2023-07-28 00:00 UTC, usmaniqbal998 commented on src/index.ts
This has been fixed

2023-07-28 00:00 UTC, usmaniqbal998 commented on src/components/index.ts
Fixed

2023-07-28 10:16 UTC, eraymeric approved these changes

2023-07-31 07:52 UTC, merged