typography development
credinvest/cred-ui pull request #14
Opened 2023-07-31 15:27 UTC by eraymeric

2023-08-01 08:27 UTC, usmaniqbal998 requested changes

2023-08-01 08:27 UTC, usmaniqbal998 commented on src/components/typography/typography.tsx
> +const colors = {
lets use global variables defined in scss for colors here

2023-08-01 08:27 UTC, usmaniqbal998 commented on src/components/typography/typography.tsx
> +    fontSize: '4rem',
can you write a callback for this repetitive code like following 
```

function variantMixin(fontSize: string, fontWeight: number, lineHeight: string, letterSpacing: string) {
  return {
    ['font-size']: fontSize,
    ['font-weight']: fontWeight,
    ['line-height']: lineHeight,
    ['letter-spacing']: letterSpacing,
  }
}
```

and then all you have to do for every variant is 
```
 heading2XL: {
    ...variantMixin('4rem', 600, '4rem', '0%'),
  },
```

2023-08-01 08:27 UTC, usmaniqbal998 commented on src/components/typography/typography.tsx
> +  font-family: 'Satoshi', sans-serif;
is this font family bundled with our package ?

2023-08-01 18:45 UTC, birkanalp commented on src/components/typography/typography.tsx
> +  font-family: 'Satoshi', sans-serif;
I think we should import font families in our projects

2023-08-03 11:36 UTC, birkanalp approved these changes

2023-08-03 11:45 UTC, usmaniqbal998 approved these changes

2023-08-03 12:40 UTC, merged